export const feedInfo = [
  {
    id: 1,
    name: "Aarav Mehta",
    username: "aarav_mehta",
    profilePic: `https://api.dicebear.com/7.x/adventurer/svg?seed=aarav_mehta`,
    content: "Just finished a new digital painting! 🎨",
    imgAttachment: "",
    timestamp: "2025-02-27 10:00 AM",
    likeCount: 25,
    commentCount: 7,
  },
  {
    id: 2,
    name: "Ishita Sharma",
    username: "ishita_sharma",
    profilePic: `https://api.dicebear.com/7.x/adventurer/svg?seed=ishita_sharma`,
    content: "Music jam session this weekend! Who's in? 🎶",
    imgAttachment: "",
    timestamp: "2025-02-27 09:45 AM",
    likeCount: 40,
    commentCount: 15,
  },
  {
    id: 3,
    name: "Kabir Verma",
    username: "kabir_verma",
    profilePic: `https://api.dicebear.com/7.x/adventurer/svg?seed=kabir_verma`,
    content: "Working on a new graphic design project 🚀",
    imgAttachment: "",
    timestamp: "2025-02-27 09:30 AM",
    likeCount: 18,
    commentCount: 5,
  },
  {
    id: 4,
    name: "Sanya Kapoor",
    username: "sanya_kapoor",
    profilePic: `https://api.dicebear.com/7.x/adventurer/svg?seed=sanya_kapoor`,
    content: "Sketching something new today ✏️",
    imgAttachment: "",
    timestamp: "2025-02-27 09:15 AM",
    likeCount: 22,
    commentCount: 9,
  },
  {
    id: 5,
    name: "Rohan Desai",
    username: "@rohan_d",
    profilePic: "https://api.dicebear.com/7.x/adventurer/svg?seed=Rohan",
    content: "Late-night coding session. 🚀 #DeveloperLife",
    imgAttachment: "",
    timestamp: "2025-02-27 09:15 AM",
    likeCount: 184,
    commentCount: 15,
  },
  {
    id: 6,
    name: "Rohan Iyer",
    username: "rohan_iyer",
    profilePic: `https://api.dicebear.com/7.x/adventurer/svg?seed=rohan_iyer`,
    content: "Photography captures the moment 📸",
    imgAttachment: "",
    timestamp: "2025-02-27 09:00 AM",
    likeCount: 30,
    commentCount: 12,
  },

  {
    id: 7,
    name: "Ananya Iyer",
    username: "@ananya_i",
    profilePic: "https://api.dicebear.com/7.x/adventurer/svg?seed=Ananya",
    content: "Sketching my next masterpiece! ✍️",
    imgAttachment: "",
    timestamp: "2025-02-26 09:15 AM",
    likeCount: 298,
    commentCount: 42,
  },
  {
    id: 8,
    name: "Devansh Kapoor",
    username: "@devansh_k",
    profilePic: "https://api.dicebear.com/7.x/adventurer/svg?seed=Devansh",
    content: "Attended a mind-blowing art exhibition today! 🎭",
    imgAttachment: "",
    timestamp: "2025-02-25 09:15 AM",
    likeCount: 121,
    commentCount: 19,
  },
  {
    id: 9,
    name: "Kavya Menon",
    username: "@kavya_m",
    profilePic: "https://api.dicebear.com/7.x/adventurer/svg?seed=Kavya",
    content: "Learning a new dance routine! 💃🔥",
    imgAttachment: "",
    timestamp: "2025-01-27 09:15 AM",
    likeCount: 210,
    commentCount: 34,
  },
];
