name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.1"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools
          firebase --version

      - name: Create Firebase Service Account Key File
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FRIENDO_5B183 }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" | base64 --decode > service-account.json
          ls -la service-account.json  # Debugging: Ensure file is created

      - name: Deploy to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service-account.json
        run: firebase deploy --only hosting --project friendo-5b183
