name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.1"

      - name: Verify Node.js version
        run: |
          echo "Node.js version: $(node -v)"
          echo "npm version: $(npm -v)"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Verify `firebase.json` exists
        run: ls -la firebase.json

      - name: Install Firebase Tools
        run: |
          npm install -g firebase-tools@latest
          firebase --version

      - name: Setup Firebase Authentication
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FRIENDO_5B183 }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" | jq '.' > service-account.json
          cat service-account.json  # Optional: Debugging to verify the JSON structure

      - name: Deploy to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service-account.json
        run: firebase deploy --only hosting --project friendo-5b183
