name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Verify Node.js version
        run: |
          node -v
          npm -v
          which node
          which npm

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Verify firebase.json exists
        run: ls -la firebase.json

      - name: Install Firebase Tools
        run: npm install -g firebase-tools@latest

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FRIENDO_5B183 }}
          channelId: live
          projectId: friendo-5b183
          entryPoint: .
          firebaseToolsVersion: latest
